kind: Service
apiVersion: v1
metadata:
  labels:
    app: nodejs-app
  name: nodejs-app-svc
  namespace: apps-ns
spec:
  type: NodePort
  ports:
  - name: nodejs-app-port
    port: 80
    targetPort: 8081
  selector:
    app: nodejs-app
