apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: apps-ns
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs
        image: gauravsj/nodejs-hello
        ports:
        - containerPort: 8081
