kind: Service
apiVersion: v1
metadata:
  labels:
    app: php-app
  name: php-app-service
spec:
  type: NodePort
  ports:
  - name: php-app-port
    port: 80
    nodePort: 30300
    targetPort: 80
  selector:
    app: php-app
